#!/usr/bin/env bash

ROOT_PATH=$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd .. && pwd)

export SC_COMPONENT_MANAGER_PATH="${SC_COMPONENT_MANAGER_PATH:-${ROOT_PATH}}"

export SC_COMPONENT_MANAGER_CMAKE_PATH="${SC_COMPONENT_MANAGER_CMAKE_PATH:-${SC_COMPONENT_MANAGER_PATH}}"
export SC_COMPONENT_MANAGER_CXX_SOURCES_PATH="${SC_COMPONENT_MANAGER_CXX_SOURCES_PATH:-${SC_COMPONENT_MANAGER_CMAKE_PATH}/src}"
export SC_COMPONENT_MANAGER_BUILD_PATH="${SC_COMPONENT_MANAGER_BUILD_PATH:-${SC_COMPONENT_MANAGER_CMAKE_PATH}/build}"
export BINARY_PATH="${BINARY_PATH:-${SC_COMPONENT_MANAGER_CMAKE_PATH}/../sc-machine/bin}"
