name: Sanitizers

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_sanitizers:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Sanitizer for sc-dictionary fs-storage - address",
            os: ubuntu-latest,
            file_memory: "Dictionary",
            sanitizer: "address",
            cc: clang,
            cxx: clang++,
          }

    steps:
      - name: Clone repositories
        run: |
            git clone https://github.com/ostis-ai/sc-machine.git 
            cd sc-machine && git checkout component_manager 
            git submodule update --init --recursive 
            cd sc-tools/sc-component-manager 
            git pull origin pull/${{ github.event.number }}/head 
            cd ../.. 
            ./scripts/install_deps_ubuntu.sh --dev

      - name: Restore build caches
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.config.os}}-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}-${{ matrix.config.file_memory }}

      - name: Build
        id: run_cmake
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
          FILE_MEMORY: ${{ matrix.config.file_memory }}
          BUILD_TYPE: ${{ matrix.config.build_type }}
          COVERAGE: OFF
          SANITIZER_TYPE: ${{ matrix.config.sanitizer }}
        run: cd sc-machine && ./scripts/ci/make-tests.sh

      - name: Run tests
        id: run_tests
        run: cd sc-machine && ./scripts/ci/run-tests.sh
